### ISSUE TITLE
Zakomentowane testy

### ISSUE THREAD

**Issue by ziobron** [BartlomiejGajdur/University-db#2]
W ogóle nie wrzucamy do repo zakomentowanego kodu.
Zakomentowane testy świadczą o tym, że jakaś funkcjonalność kiedyś działała, ale teraz jest zepsuta

**Comment by BartlomiejGajdur** [comment]
Fixed

**Comment by ziobron** [comment]
A miałem nadzieję, że raczej zrobisz coś, żeby je odkomentować, a nie wyrzucisz :)
Przydałyby się testy, tym bardziej że w README.md masz opisane jak je puścić.

**Comment by BartlomiejGajdur** [comment]
Zapisałem sobie w notatniku, ze mam je zrobić, ale na ten moment wyjeżdżam na kilka dni a nie chciałem mieć żadnego Issue otwartego. Może to zła praktyka :)

**Comment by BartlomiejGajdur** [comment]
Done
