### ISSUE TITLE
Dodaj aliasy nazw

### ISSUE THREAD

**Issue by ziobron** [BartlomiejGajdur/University-db#3]
W kodzie są długie nazwy typów takie jak `std::vector<std::shared_ptr<Person>>`. Warto dać im aliasy:

```cpp
using PersonPtr = std::shared_ptr<Person>;
using PersonVector = std::vector<PersonPtr>;
```

**Comment by BartlomiejGajdur** [comment]
Added suggested aliases and a few more.
